services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL=https://twoja-domena.pl/
      - N8N_BASIC_AUTH_ACTIVE=false
      - GENERIC_TIMEZONE=Europe/Warsaw
